<?php

header('Content-Type: text/html; charset=UTF-8');

echo '<!DOCTYPE html>'
    .'<html>'
        .'<head>'
            .'<title>rich-textarea</title>'
            .'<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />'
            .'<link rel="stylesheet" type="text/css" href="index.css" />'
        .'</head>'
        .'<body>'
            .'<div>'
                .'<button id="deleteTextButton">deleteText()</button>'
                .'<button id="disableButton">disable()</button>'
                .'<button id="enableButton">enable()</button>'
                .'<button id="focusButton">focus()</button>'
                .'<button id="redoButton">redo()</button>'
                .'<button id="selectButton">select()</button>'
                .'<button id="undoButton">undo()</button>'
            .'</div>'
            .'<div>'
                .'<span>console.log(</span>'
                .'<button id="canDeleteTextButton">canDeleteText()</button>'
                .'<button id="canRedoButton">canRedo()</button>'
                .'<button id="canUndoButton">canUndo()</button>'
                .'<button id="getScrollBarHeightButton">getScrollBarHeight()</button>'
                .'<button id="getScrollTopButton">getScrollTop()</button>'
                .'<button id="getSelectedTextButton">getSelectedText()</button>'
                .'<button id="getSelectionDirectionButton">getSelectionDirection()</button>'
                .'<button id="getSelectionEndButton">getSelectionEnd()</button>'
                .'<button id="getSelectionStartButton">getSelectionStart()</button>'
                .'<button id="getValueButton">getValue()</button>'
                .'<span>)</span>'
            .'</div>'
            .'<div>'
                .'<button id="findNextButton">findNext</button>'
                .'<button id="findPrevButton">findPrev</button>'
                .'<button id="goToLineButton">goToLine</button>'
                .'<button id="moveSelectionEndButton">moveSelectionEnd</button>'
                .'<button id="moveSelectionStartButton">moveSelectionStart</button>'
                .'<button id="pasteButton">paste</button>'
                .'<button id="replaceSelectedTextButton">replaceSelectedText</button>'
                .'<button id="setValueButton">setValue</button>'
                .'<span>(</span>'
                .'<input type="text" id="oneArgInput" />'
                .'<span>)</span>'
            .'</div>'
            .'<div>'
                .'<button id="replaceAllButton">replaceAll</button>'
                .'<button id="setSelectionRangeButton">setSelectionRange</button>'
                .'<span>(</span>'
                .'<input type="text" id="twoArgInput1" />'
                .'<span>, </span>'
                .'<input type="text" id="twoArgInput2" />'
                .'<span>)</span>'
            .'</div>'
            .'<div>'
            .'<script type="text/javascript" src="../../javascript/ArrayCall.js"></script>'
            .'<script type="text/javascript" src="../../javascript/KeyCodes.js"></script>'
            .'<script type="text/javascript" src="../../javascript/Languages.js"></script>'
            .'<script type="text/javascript" src="../../javascript/Preferences.js"></script>'
            .'<script type="text/javascript" src="../../javascript/Languages/de/Terms.js"></script>'
            .'<script type="text/javascript" src="../../javascript/Languages/en/Terms.js"></script>'
            .'<script type="text/javascript" src="../../javascript/Languages/ka/Terms.js"></script>'
            .'<script type="text/javascript" src="../../javascript/RichTextarea/Textarea.js"></script>'
            .'<script type="text/javascript" src="index.js"></script>'
        .'</body>'
    .'</html>';
